spring.application.name=tvlicensing

spring.datasource.url=jdbc:sqlserver://tv-licence-fine.database.windows.net:1433;database=tv-licence-fine-database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
spring.datasource.username=billy@tv-licence-fine
spring.datasource.password=thisismyPassword1!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jpa.open-in-view=false




